# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hello There
email: dont@spam.me
description: > # this means to ignore newlines until "baseurl:"
  Some descriptive description that describes this site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bagonyi.github.io" # the base hostname & protocol for your site
twitter_username: dbagonyi
github_username:  bagonyi

# Build settings
markdown: kramdown
